title: Hulman Lab
subtitle: Machine learning with a clinical purpose
description: An engaging 1-3 sentence description of your lab.
header: images/background.png
footer: images/background.png
links:
  email: adahul@rm.dk
  orcid: 0000-0002-3969-1000
  google-scholar: w5_yAkUAAAAJ&hl
  twitter: adamhulman
defaults:
  - scope:
      path: ""
    values:
      layout: default
  - scope:
      type: members
    values:
      layout: member
  - scope:
      type: posts
    values:
      layout: post
collections:
  members:
    output: true
  posts:
    output: true
plugins:
  - jekyll-spaceship
  - jekyll-sitemap
  - jekyll-redirect-from
  - jekyll-feed
  - jekyll-last-modified-at
highlighter: rouge
theme: null
sass:
  sass_dir: _styles
include:
  - _styles
  - _scripts
exclude:
  - README.md
  - LICENSE.md
  - CITATION.cff
email: adahul@rm.dk
twitter: Adam Hulman
instagram: adam Hulman
