title: Hulman Lab
subtitle: AI and Machinlearning predicitonmodel for clinical purpose
description: An engaging 1-3 sentence description of your lab.
header: images/background.jpg
footer: images/background.jpg
links:
  email: contact@your-lab.com
  orcid: 0000-0002-3969-1000
  google-scholar: w5_yAkUAAAAJ&hl
  github: your-lab
  twitter: https://twitter.com/adamhulman?lang=da
  youtube: YourLabChannel
defaults:
  - scope:
      path: ""
    values:
      layout: default
  - scope:
      type: members
    values:
      layout: member
  - scope:
      type: posts
    values:
      layout: post
collections:
  members:
    output: true
  posts:
    output: true
plugins:
  - jekyll-spaceship
  - jekyll-sitemap
  - jekyll-redirect-from
  - jekyll-feed
  - jekyll-last-modified-at
highlighter: rouge
theme: null
sass:
  sass_dir: _styles
include:
  - _styles
  - _scripts
exclude:
  - README.md
  - LICENSE.md
  - CITATION.cff
email: contact@ManuThomasen.com
github: Adam Hulman
twitter: Adam Hulman
instagram: ManuThomasen
youtube: ManuThomasen
